CREATE DATABASE EMPRESA
GO
USE EMPRESA
GO


CREATE TABLE CLIENTES(
ID INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(80) NOT NULL,
CREDITO MONEY NOT NULL,
DEUDA MONEY NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
VIGENCIA CHAR(1) NOT NULL
)

INSERT CLIENTES VALUES ('JOSÉ PANCHO', 155.55, 10.55, 'SINALOA', 'A')

SELECT * FROM CLIENTES

